apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq01
  labels:
    app: vprormq01
spec:
  selector:
    matchLabels:
      app: vprormq01  # This should match the labels in template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        app: vprormq01  # This should match the labels in selector.matchLabels
    spec:
      containers:
      - name: vprormq01
        image: rabbitmq
        ports:
        - name: vprormq01-port
          containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: rmq-pass
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"